/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\libo\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\_@vuepress_core@1.4.0@@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "C:\\Users\\libo\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\_@vuepress_plugin-active-header-links@1.4.0@@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "C:\\Users\\libo\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\_@vuepress_plugin-nprogress@1.4.0@@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m3 from "C:\\Users\\libo\\AppData\\Roaming\\npm\\node_modules\\vuepress\\node_modules\\_vuepress-plugin-smooth-scroll@0.0.3@vuepress-plugin-smooth-scroll\\lib\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]