/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "李博的个人网站",
  "description": "李博的个人网站",
  "base": "/",
  "pages": [
    {
      "title": "第一个页面",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8148e78e",
      "path": "/"
    },
    {
      "title": "关于页面",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-5a683a62",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "地方上的上的",
          "slug": "地方上的上的"
        }
      ]
    }
  ],
  "themeConfig": {
    "displayAllHeaders": true,
    "smoothScroll": true,
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "About",
        "link": "/about.html"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "sidebar": [
      "/",
      "/about"
    ]
  }
}